### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by aeharding** [emibcn/service-worker-updater#54]
Hello! Thanks for this great project.

I was just wondering - would you be open to converting this project to Typescript? If so, I'd be willing to make a PR for it. 🙂

**Comment by emibcn** [comment]
Hello @aeharding !
I am open to convert this project to TypeScript and I will appreciate a PR if you have the time to do it. I will review it once you told me to.

Thanks a lot for the contribution!!

**Comment by emibcn** [comment]
Updated README thanking @aeharding . Publishing new version patch for uploading this to NPM.
