### ISSUE TITLE
Question: persistent update notification

### ISSUE THREAD

**Issue by chrisharrison** [emibcn/service-worker-updater#74]
The `newServiceWorkerDetected` returns `true` when an update is detected. But if you refresh the app before applying the update, `newServiceWorkerDetected` returns `false` and doesn't return `true` again. So essentially it's a one time chance to update, if you miss it, that's it!

Is this expected behaviour? And would you have an elegant solution to that?

My naïve solution at this stage is to have the component write something to a persistent store (local storage?) so upon refresh the fact that the app needs an update is still in state and to continue showing the update component. After the update happens (after calling `onLoadNewServiceWorkerAccept`) that persisted value would be removed.

**Comment by emibcn** [comment]
Hi @chrisharrison !
Good question, I didn't realized until now. You can create a HOC to get the data and save it into a cookie/localStorage/whatever is your current local storage solution. Anyway, the component can offer a default solution, several ones (and a parameter to choice between them) or, at least, some code examples to implement it. I will take a look into it in the next few days.

For sure, if anyone have more ideas on it or wants to take it to make a PR, just comment.
